baseURL: "https://lustrous-clafoutis-0b6e4b.netlify.app"
languageCode: en-us
title: DevMod
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "DevMod" # optional default will be site title
    subtitle: "Minecraft server owner & developer"
    imageUrl: "https://files.dotmix.pw/.assets/icons/dotmix-full.png" # optional
    imageTitle: "DevLogo" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Статьи
        url: "/posts"
      - name: Github
        url: "https://github.com/"
  # socialIcons:
  #   - name: vk
  #     url: "https://facebook.com/"
  #   - name: vkontakte
  #     url: "https://twitter.com/"
  #   - name: github
  #     url: "https://github.com/"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: posts
      name: Статьи
      url: /posts/
      weight: 10
    - identifier: about
      name: Обо мне
      url: /about/
      weight: 20
