baseURL: "https://lustrous-clafoutis-0b6e4b.netlify.app"
languageCode: ru-ru
title: DevMod
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "DevMod" # optional default will be site title
    subtitle: "Minecraft server owner & developer"
    imageUrl: "https://media3.giphy.com/media/4ilFRqgbzbx4c/200.gif" # optional
    imageTitle: "DevLogo" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Статьи
        url: "/posts"
      - name: Telegram
        url: "https://github.com/"
  # socialIcons:
  #   - name: telegram
  #     url: "https://google.com/"
  #   - name: vkontakte
  #     url: "https://twitter.com/"
  #   - name: github
  #     url: "https://github.com/"

  cover:
    linkFullImages: false

  # ShowBreadCrumbs: true

  ShowCodeCopyButtons: true

menu:
  main:
    - identifier: posts
      name: Статьи
      url: /posts/
      weight: 10
    - identifier: about
      name: Обо мне
      url: /about/
      weight: 20
